/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timpaulseo.timpaulupdate;

import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Bunnyspa
 */
public class MainFrame extends javax.swing.JFrame {

    private static final String PATH = new File("").getAbsolutePath();
    private static final String FILENAME = "timpaul";
    private static final String URL_JAR = "https://github.com/timpaulseo/timpaulseo.github.io/releases/latest/download/timpaul.jar";
    private final Image favicon = new ImageIcon(getClass().getResource("/resources/favicon.png")).getImage();

    /**
     * Creates new form MainDialog
     */
    public MainFrame() {
        initComponents();
        // System.out.println(getClass().getResource("/resources/favicon.png"));
        init();
    }

    private void init() {
        setIconImage(favicon);
        setLocationRelativeTo(null);
    }

    public void start() {
        download();
        System.exit(0);
    }

    private void download() {
        try (BufferedInputStream inputStream = new BufferedInputStream(new URL(URL_JAR).openStream());
                FileOutputStream fileOS = new FileOutputStream(FILENAME + ".download")) {
            byte data[] = new byte[4096];
            int byteContent;
            while ((byteContent = inputStream.read(data, 0, 4096)) != -1) {
                fileOS.write(data, 0, byteContent);
                fileOS.flush();
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "다운로드중 오류가 발생했습니다.",
                    "오류", JOptionPane.ERROR_MESSAGE);
            return;
        }
        new File(FILENAME + ".jar").delete();
        new File(FILENAME + ".download").renameTo(new File(FILENAME + ".jar"));
        runProgram();
    }

    private static void runProgram() {
        try {
            String exePath = PATH + "\\" + FILENAME + ".jar";
            ProcessBuilder process = new ProcessBuilder(".\\jre\\bin\\java.exe", "-jar", exePath);
            process.directory(new File(PATH + "\\"));
            process.start();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

//    private static void openWeb(Component c) {
//        try {
//            Desktop.getDesktop().browse(new URI(URL_JAR));
//        } catch (IOException | URISyntaxException ex) {
//            JOptionPane.showMessageDialog(c,
//                    "다운로드중 오류가 발생했습니다.",
//                    "오류", JOptionPane.ERROR_MESSAGE);
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("팀폴 업데이트");

        aLabel.setFont(aLabel.getFont().deriveFont(aLabel.getFont().getSize()+13f));
        aLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aLabel.setText("업데이트중....");
        aLabel.setPreferredSize(new java.awt.Dimension(300, 16));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLabel;
    private javax.swing.JButton cancelButton;
    // End of variables declaration//GEN-END:variables
}
